/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EvidenceIndexRouteImport } from './routes/evidence.index'
import { Route as EvidenceTrackersIndexRouteImport } from './routes/evidence.trackers.index'
import { Route as EvidenceTrackersSlugRouteImport } from './routes/evidence.trackers.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceIndexRoute = EvidenceIndexRouteImport.update({
  id: '/evidence/',
  path: '/evidence/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceTrackersIndexRoute = EvidenceTrackersIndexRouteImport.update({
  id: '/evidence/trackers/',
  path: '/evidence/trackers/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceTrackersSlugRoute = EvidenceTrackersSlugRouteImport.update({
  id: '/evidence/trackers/$slug',
  path: '/evidence/trackers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evidence/': typeof EvidenceIndexRoute
  '/evidence/trackers/$slug': typeof EvidenceTrackersSlugRoute
  '/evidence/trackers/': typeof EvidenceTrackersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evidence': typeof EvidenceIndexRoute
  '/evidence/trackers/$slug': typeof EvidenceTrackersSlugRoute
  '/evidence/trackers': typeof EvidenceTrackersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evidence/': typeof EvidenceIndexRoute
  '/evidence/trackers/$slug': typeof EvidenceTrackersSlugRoute
  '/evidence/trackers/': typeof EvidenceTrackersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/evidence/' | '/evidence/trackers/$slug' | '/evidence/trackers/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/evidence' | '/evidence/trackers/$slug' | '/evidence/trackers'
  id:
    | '__root__'
    | '/'
    | '/evidence/'
    | '/evidence/trackers/$slug'
    | '/evidence/trackers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvidenceIndexRoute: typeof EvidenceIndexRoute
  EvidenceTrackersSlugRoute: typeof EvidenceTrackersSlugRoute
  EvidenceTrackersIndexRoute: typeof EvidenceTrackersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/': {
      id: '/evidence/'
      path: '/evidence'
      fullPath: '/evidence/'
      preLoaderRoute: typeof EvidenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/trackers/': {
      id: '/evidence/trackers/'
      path: '/evidence/trackers'
      fullPath: '/evidence/trackers/'
      preLoaderRoute: typeof EvidenceTrackersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/trackers/$slug': {
      id: '/evidence/trackers/$slug'
      path: '/evidence/trackers/$slug'
      fullPath: '/evidence/trackers/$slug'
      preLoaderRoute: typeof EvidenceTrackersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvidenceIndexRoute: EvidenceIndexRoute,
  EvidenceTrackersSlugRoute: EvidenceTrackersSlugRoute,
  EvidenceTrackersIndexRoute: EvidenceTrackersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
