/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as AboutBoardRouteImport } from './routes/about.board'
import { Route as AboutResearchLeadershipRouteImport } from './routes/about.research-leadership'
import { Route as ConveningIndexRouteImport } from './routes/convening.index'
import { Route as ConveningSlugRouteImport } from './routes/convening.$slug'
import { Route as EvidenceIndexRouteImport } from './routes/evidence.index'
import { Route as EvidenceCorrectionsRouteImport } from './routes/evidence.corrections'
import { Route as EvidenceMethodsRouteImport } from './routes/evidence.methods'
import { Route as LadderIndexRouteImport } from './routes/ladder.index'
import { Route as LadderSlugRouteImport } from './routes/ladder.$slug'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes.index'
import { Route as ProgrammesSlugRouteImport } from './routes/programmes.$slug'
import { Route as EvidencePublicationsIndexRouteImport } from './routes/evidence.publications.index'
import { Route as EvidencePublicationsSlugRouteImport } from './routes/evidence.publications.$slug'
import { Route as EvidenceTrackersIndexRouteImport } from './routes/evidence.trackers.index'
import { Route as EvidenceTrackersSlugRouteImport } from './routes/evidence.trackers.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutBoardRoute = AboutBoardRouteImport.update({
  id: '/about/board',
  path: '/about/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutResearchLeadershipRoute = AboutResearchLeadershipRouteImport.update({
  id: '/about/research-leadership',
  path: '/about/research-leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const ConveningIndexRoute = ConveningIndexRouteImport.update({
  id: '/convening/',
  path: '/convening/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConveningSlugRoute = ConveningSlugRouteImport.update({
  id: '/convening/$slug',
  path: '/convening/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceIndexRoute = EvidenceIndexRouteImport.update({
  id: '/evidence/',
  path: '/evidence/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceCorrectionsRoute = EvidenceCorrectionsRouteImport.update({
  id: '/evidence/corrections',
  path: '/evidence/corrections',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceMethodsRoute = EvidenceMethodsRouteImport.update({
  id: '/evidence/methods',
  path: '/evidence/methods',
  getParentRoute: () => rootRouteImport,
} as any)
const LadderIndexRoute = LadderIndexRouteImport.update({
  id: '/ladder/',
  path: '/ladder/',
  getParentRoute: () => rootRouteImport,
} as any)
const LadderSlugRoute = LadderSlugRouteImport.update({
  id: '/ladder/$slug',
  path: '/ladder/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/programmes/',
  path: '/programmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesSlugRoute = ProgrammesSlugRouteImport.update({
  id: '/programmes/$slug',
  path: '/programmes/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidencePublicationsIndexRoute =
  EvidencePublicationsIndexRouteImport.update({
    id: '/evidence/publications/',
    path: '/evidence/publications/',
    getParentRoute: () => rootRouteImport,
  } as any)
const EvidencePublicationsSlugRoute =
  EvidencePublicationsSlugRouteImport.update({
    id: '/evidence/publications/$slug',
    path: '/evidence/publications/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const EvidenceTrackersIndexRoute = EvidenceTrackersIndexRouteImport.update({
  id: '/evidence/trackers/',
  path: '/evidence/trackers/',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceTrackersSlugRoute = EvidenceTrackersSlugRouteImport.update({
  id: '/evidence/trackers/$slug',
  path: '/evidence/trackers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about/board': typeof AboutBoardRoute
  '/about/research-leadership': typeof AboutResearchLeadershipRoute
  '/convening/$slug': typeof ConveningSlugRoute
  '/evidence/corrections': typeof EvidenceCorrectionsRoute
  '/evidence/methods': typeof EvidenceMethodsRoute
  '/ladder/$slug': typeof LadderSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/about/': typeof AboutIndexRoute
  '/convening/': typeof ConveningIndexRoute
  '/evidence/': typeof EvidenceIndexRoute
  '/ladder/': typeof LadderIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/evidence/publications/$slug': typeof EvidencePublicationsSlugRoute
  '/evidence/trackers/$slug': typeof EvidenceTrackersSlugRoute
  '/evidence/publications/': typeof EvidencePublicationsIndexRoute
  '/evidence/trackers/': typeof EvidenceTrackersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about/board': typeof AboutBoardRoute
  '/about/research-leadership': typeof AboutResearchLeadershipRoute
  '/convening/$slug': typeof ConveningSlugRoute
  '/evidence/corrections': typeof EvidenceCorrectionsRoute
  '/evidence/methods': typeof EvidenceMethodsRoute
  '/ladder/$slug': typeof LadderSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/about': typeof AboutIndexRoute
  '/convening': typeof ConveningIndexRoute
  '/evidence': typeof EvidenceIndexRoute
  '/ladder': typeof LadderIndexRoute
  '/programmes': typeof ProgrammesIndexRoute
  '/evidence/publications/$slug': typeof EvidencePublicationsSlugRoute
  '/evidence/trackers/$slug': typeof EvidenceTrackersSlugRoute
  '/evidence/publications': typeof EvidencePublicationsIndexRoute
  '/evidence/trackers': typeof EvidenceTrackersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/board': typeof AboutBoardRoute
  '/about/research-leadership': typeof AboutResearchLeadershipRoute
  '/convening/$slug': typeof ConveningSlugRoute
  '/evidence/corrections': typeof EvidenceCorrectionsRoute
  '/evidence/methods': typeof EvidenceMethodsRoute
  '/ladder/$slug': typeof LadderSlugRoute
  '/programmes/$slug': typeof ProgrammesSlugRoute
  '/about/': typeof AboutIndexRoute
  '/convening/': typeof ConveningIndexRoute
  '/evidence/': typeof EvidenceIndexRoute
  '/ladder/': typeof LadderIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
  '/evidence/publications/$slug': typeof EvidencePublicationsSlugRoute
  '/evidence/trackers/$slug': typeof EvidenceTrackersSlugRoute
  '/evidence/publications/': typeof EvidencePublicationsIndexRoute
  '/evidence/trackers/': typeof EvidenceTrackersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/board'
    | '/about/research-leadership'
    | '/convening/$slug'
    | '/evidence/corrections'
    | '/evidence/methods'
    | '/ladder/$slug'
    | '/programmes/$slug'
    | '/about/'
    | '/convening/'
    | '/evidence/'
    | '/ladder/'
    | '/programmes/'
    | '/evidence/publications/$slug'
    | '/evidence/trackers/$slug'
    | '/evidence/publications/'
    | '/evidence/trackers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about/board'
    | '/about/research-leadership'
    | '/convening/$slug'
    | '/evidence/corrections'
    | '/evidence/methods'
    | '/ladder/$slug'
    | '/programmes/$slug'
    | '/about'
    | '/convening'
    | '/evidence'
    | '/ladder'
    | '/programmes'
    | '/evidence/publications/$slug'
    | '/evidence/trackers/$slug'
    | '/evidence/publications'
    | '/evidence/trackers'
  id:
    | '__root__'
    | '/'
    | '/about/board'
    | '/about/research-leadership'
    | '/convening/$slug'
    | '/evidence/corrections'
    | '/evidence/methods'
    | '/ladder/$slug'
    | '/programmes/$slug'
    | '/about/'
    | '/convening/'
    | '/evidence/'
    | '/ladder/'
    | '/programmes/'
    | '/evidence/publications/$slug'
    | '/evidence/trackers/$slug'
    | '/evidence/publications/'
    | '/evidence/trackers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutBoardRoute: typeof AboutBoardRoute
  AboutResearchLeadershipRoute: typeof AboutResearchLeadershipRoute
  ConveningSlugRoute: typeof ConveningSlugRoute
  EvidenceCorrectionsRoute: typeof EvidenceCorrectionsRoute
  EvidenceMethodsRoute: typeof EvidenceMethodsRoute
  LadderSlugRoute: typeof LadderSlugRoute
  ProgrammesSlugRoute: typeof ProgrammesSlugRoute
  AboutIndexRoute: typeof AboutIndexRoute
  ConveningIndexRoute: typeof ConveningIndexRoute
  EvidenceIndexRoute: typeof EvidenceIndexRoute
  LadderIndexRoute: typeof LadderIndexRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
  EvidencePublicationsSlugRoute: typeof EvidencePublicationsSlugRoute
  EvidenceTrackersSlugRoute: typeof EvidenceTrackersSlugRoute
  EvidencePublicationsIndexRoute: typeof EvidencePublicationsIndexRoute
  EvidenceTrackersIndexRoute: typeof EvidenceTrackersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/board': {
      id: '/about/board'
      path: '/about/board'
      fullPath: '/about/board'
      preLoaderRoute: typeof AboutBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/research-leadership': {
      id: '/about/research-leadership'
      path: '/about/research-leadership'
      fullPath: '/about/research-leadership'
      preLoaderRoute: typeof AboutResearchLeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convening/': {
      id: '/convening/'
      path: '/convening'
      fullPath: '/convening/'
      preLoaderRoute: typeof ConveningIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convening/$slug': {
      id: '/convening/$slug'
      path: '/convening/$slug'
      fullPath: '/convening/$slug'
      preLoaderRoute: typeof ConveningSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/': {
      id: '/evidence/'
      path: '/evidence'
      fullPath: '/evidence/'
      preLoaderRoute: typeof EvidenceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/corrections': {
      id: '/evidence/corrections'
      path: '/evidence/corrections'
      fullPath: '/evidence/corrections'
      preLoaderRoute: typeof EvidenceCorrectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/methods': {
      id: '/evidence/methods'
      path: '/evidence/methods'
      fullPath: '/evidence/methods'
      preLoaderRoute: typeof EvidenceMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ladder/': {
      id: '/ladder/'
      path: '/ladder'
      fullPath: '/ladder/'
      preLoaderRoute: typeof LadderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ladder/$slug': {
      id: '/ladder/$slug'
      path: '/ladder/$slug'
      fullPath: '/ladder/$slug'
      preLoaderRoute: typeof LadderSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/programmes'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/$slug': {
      id: '/programmes/$slug'
      path: '/programmes/$slug'
      fullPath: '/programmes/$slug'
      preLoaderRoute: typeof ProgrammesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/publications/': {
      id: '/evidence/publications/'
      path: '/evidence/publications'
      fullPath: '/evidence/publications/'
      preLoaderRoute: typeof EvidencePublicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/publications/$slug': {
      id: '/evidence/publications/$slug'
      path: '/evidence/publications/$slug'
      fullPath: '/evidence/publications/$slug'
      preLoaderRoute: typeof EvidencePublicationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/trackers/': {
      id: '/evidence/trackers/'
      path: '/evidence/trackers'
      fullPath: '/evidence/trackers/'
      preLoaderRoute: typeof EvidenceTrackersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence/trackers/$slug': {
      id: '/evidence/trackers/$slug'
      path: '/evidence/trackers/$slug'
      fullPath: '/evidence/trackers/$slug'
      preLoaderRoute: typeof EvidenceTrackersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutBoardRoute: AboutBoardRoute,
  AboutResearchLeadershipRoute: AboutResearchLeadershipRoute,
  ConveningSlugRoute: ConveningSlugRoute,
  EvidenceCorrectionsRoute: EvidenceCorrectionsRoute,
  EvidenceMethodsRoute: EvidenceMethodsRoute,
  LadderSlugRoute: LadderSlugRoute,
  ProgrammesSlugRoute: ProgrammesSlugRoute,
  AboutIndexRoute: AboutIndexRoute,
  ConveningIndexRoute: ConveningIndexRoute,
  EvidenceIndexRoute: EvidenceIndexRoute,
  LadderIndexRoute: LadderIndexRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
  EvidencePublicationsSlugRoute: EvidencePublicationsSlugRoute,
  EvidenceTrackersSlugRoute: EvidenceTrackersSlugRoute,
  EvidencePublicationsIndexRoute: EvidencePublicationsIndexRoute,
  EvidenceTrackersIndexRoute: EvidenceTrackersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
